#!/usr/bin/env bash
# Update the package repository and install Nginx

apt-get -y update
apt-get -y install nginx

# Allowing 'HTTP'
ufw allow 'Nginx HTTP'

# Output 'Hello world'
echo "Hello World!" > /var/www/html/index.nginx-debian.html

service nginx start

