#!/usr/bin/env bash
# Update the package repository and install Nginx

sudo apt-get -y update
sudo apt-get -y install nginx

# Allowing 'HTTP'
sudo ufw allow 'Nginx HTTP'

# Output 'Hello world'
echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo service nginx start
