#!/usr/bin/env bash
# Script configures a new Ubuntu machine to Perform a '301-redirection'

# Updating packages before installing
sudo apt-get update
# sudo apt-get install -y nginx

sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF

server {
        listen 80;
        listen [::]:80;
        server_name _;

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
}
EOF

sudo service nginx restart
