#!/usr/bin/env bash
# A script that displays information about my sub-domains

subdomain_info() {
    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ $# == 1 ]; then
    subdomain_info "$1" "www"
    subdomain_info "$1" "lb-01"
    subdomain_info "$1" "web-01"
    subdomain_info "$1" "web-02"

elif [ $# == 2 ]; then

    subdomain_info "$1" "$2"
fi

