#!/usr/bin/env bash
# Backing up and compress my databases

day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
tar_file="$day-$month-$year.tar.gz"

# Use 'sudo su' or 'sudo' on any errors
mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$tar_file" backup.sql
