#!/usr/bin/env bash
# Configuring servers to listen on port 80 for all servers active IPv4 IPs
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo kill -9 "$(cat /var/run/nginx.pid)"
