#!/usr/bin/env bash
# Loops from 1 to 10 and displays:
#   "bad luck" on the 4th iteration
#   "good luck" on the 8th iteration
#   "Best School" for the other iterations

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 3 ]
  then
    echo "bad luck"
  elif [ $count -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( count++ ))
done
