#!/usr/bin/env bash
# Fixing bugs in the server

chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default

sudo /etc/init.d/apache2 stop

su nginx -s /bin/bash -c 'service nginx restart'
